version: '3.8'

services:

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - psql_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
    - "5432:5432"

  migrations:
    build:
      context: .
      dockerfile: dockerfile
    image: altec3/thesis
    environment:
      DB_HOST: db
    volumes:
      - ./.env:/server/.env
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  api:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    environment:
      DB_HOST: db
    volumes:
      - ./.env:/server/.env
      - static:/server/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: gunicorn todolist.wsgi:application --bind 0.0.0.0:8000

  front:
    image: sermalenk/skypro-front:lesson-36
    volumes:
      - ./front_config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - db
      - api

volumes:
  psql_data:
  static:
