# Generated by Django 4.1.4 on 2023-01-23 04:53

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
    # Для загрузки кода моделей используется специальный метод apps.get_model
    # Он позволяет загрузить ровно то состояние модели, которое было на момент применения этой миграции
    # Импортировать настоящие классы – плохая практика
    # так как в будущем вы можете удалить/переименовать эти модели, и тогда у вас будут ошибки импорта

    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    Category = apps.get_model('goals', 'Category')

    with transaction.atomic():  # Применяем все изменения одной транзакцией
        for user in User.objects.all():  # Для каждого пользователя
            # Создаем доску
            new_board = Board.objects.create(
                title='Мои цели',
                created=timezone.now(),
                updated=timezone.now()
            )
            # Создаем участника доски (владельца)
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=timezone.now(),
                updated=timezone.now()
            )

            # Проставляем всем категориям пользователя его доску
            Category.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_board_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
