version: '3.8'

services:

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  collectstatic:
    image: altec3/thesis:latest
    env_file:
      - .env
    volumes:
      - static:/server/static
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "manage.py", "collectstatic", "-c", "--no-input"]

  api:
    image: altec3/thesis:latest
    restart: always
    env_file:
      - .env
    depends_on:
      collectstatic:
        condition: service_completed_successfully
    command: ["gunicorn", "todolist.wsgi:application", "-w", "4", "--bind", "0.0.0.0:8000"]

  bot:
    image: altec3/thesis:latest
    restart: always
    env_file:
      - .env
    depends_on:
      api:
        condition: service_started
    command: ["python3", "manage.py", "runbot"]

  front:
    image: altec3/thesis-front:https-latest
    volumes:
      - static:/usr/share/nginx/html/static/
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=lesnikov-a.ga
      - CERTBOT_EMAIL=admin@mail.ru
    depends_on:
      bot:
        condition: service_started

volumes:
  psql_data:
    driver: local
  static:
    driver: local
  letsencrypt:
    driver: local
