# Generated by Django 4.1.4 on 2023-02-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_boardparticipant_options_and_more'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create_command', models.BooleanField(default=False, verbose_name='Выполняется команда /create')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_chat_state', to='goals.category', verbose_name='Категория')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_chat_state', to='bot.tguser', verbose_name='TG пользователь')),
            ],
            options={
                'verbose_name': 'Состояние чата',
                'verbose_name_plural': 'Состояния чата',
            },
        ),
    ]
