name: Tests thesis_project
run-name: Running thesis project tests by ${{ github.actor }}

on:
  push:
    branches:
      - fixes
jobs:

  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.10'
      POETRY_VERSION: 1.3.1
      DJANGO_SK: django_secret_key
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      VK_OAUTH2_KEY: 12345678
      VK_OAUTH2_SECRET: vk_oauth2_secret
      TG_TOKEN: tg_token
    services:
      postgres:
        image: postgres:12.4-alpine
        env:
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 3s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      -
        name: clone code
        uses: actions/checkout@v3
      -
        name: install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      -
        name: install Poetry ${{ env.POETRY_VERSION }}
        run: |
          python -m pip install poetry==${{ env.POETRY_VERSION }}
      -
        name: install dependencies
        run: |
          python -m poetry install --with test
      -
        name: run tests
        working-directory: ./todolist
        run: |
          python -m poetry run pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=todolist \
          tests/ | tee pytest-coverage.txt
      -
        name: pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./todolist/pytest-coverage.txt
          junitxml-path: ./todolist/pytest.xml
